# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty

# Setup
title:               Levent Erkök
tagline:             Levent Erkök
url:                 http://leventerkok.github.io/
paginate:            1
baseurl:             ""

# Assets
#
# We specify the directory for Jekyll so we can use @imports.
sass:
  sass_dir:          _sass
  style:            :compressed

# About/contact
author:
  name:              Levent Erkök
  url:               http://leventerkok.github.io/
  email:             erkokl@gmail.com

# Custom vars
version:             2.0.0
github:
  repo:              http://leventerkok.github.io/

# Gems
plugins: [jekyll-paginate, jekyll-gist]
